### ISSUE TITLE
BUG: wrong alignment of SKILLS section

### ISSUE THREAD

**Issue by shehryardev** [shehryardev/reactjs-portfolio#1]
**Describe the bug**
The alignment of the SKILLS section is between left and center

**To Reproduce**
1. Go to the 'Home page'
2. Have a look over the SKLLS section

**Expected behavior**
The alignment of the SKILLS section should be on the left

**Screenshots**
![image](https://github.com/shehryardev/reactjs-portfolio/assets/87665324/4b204c28-3681-4019-af2f-584892a572f2)

**Desktop**:
OS: [windows]
Browser: [Chrome]

**Comment by khoadangtran** [comment]
Hello, Can I Assign?
